Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,7 @@ on:
 
 jobs:
   build:
-    runs-on: macos-latest  # Используем macOS для выполнения
+    runs-on: macos-latest
 
     steps:
       - uses: actions/checkout@v4
@@ -26,7 +26,14 @@ jobs:
       - name: Build and Test
         run: |
           echo "Running build and tests..."
-          xcodebuild -scheme MyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' build test
+          xcodebuild -scheme chilin1 -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' build test
+
+      - name: Check Test Results
+        run: |
+          if grep -q "** TEST FAILED **" "/path/to/your/test/results"; then
+            echo "Test failed. Check the logs for more details."
+            exit 1
+          fi
 
       - name: Notify Telegram on Failure
         if: failure()
