Update notify.yml

diff --git a/.github/workflows/notify.yml b/.github/workflows/notify.yml
--- a/.github/workflows/notify.yml
+++ b/.github/workflows/notify.yml
@@ -15,15 +15,20 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
+      - name: Set up Xcode
+        uses: maxim-lobanov/setup-xcode@v1
+        with:
+          xcode-version: '12.4'
+
       - name: Run Tests
         run: |
           echo "Running tests..."
-          # Добавьте вашу команду для запуска тестов здесь
-          # Например: npm test
+          xcodebuild -scheme MyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' test
+          exit 1  # Искусственно вызываем ошибку для тестирования уведомлений
 
       - name: Check Test Results
         if: failure()
-        run: echo "Tests failed" # Здесь вы можете добавить команды для обработки ошибок, если нужно
+        run: echo "Tests failed"
 
       - name: Notify Telegram on Failure
         if: failure()
@@ -31,4 +36,4 @@ jobs:
           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
           CHAT_ID: 546454208
         run: |
-          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage -d chat_id=${{ env.CHAT_ID }} -d text="❌ Build failed in repository: ${{ github.repository }}. Commit: ${{ github.sha }}. Check details: ${{ github.run_url }}"
+          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id=${{ env.CHAT_ID }} -d text="❌ Build failed in repository: ${{ github.repository }}. Commit: ${{ github.sha }}. Check details: ${{ github.run_url }}"
